### ISSUE TITLE
Consider some items under SecureFox for the Firefox Secure proposal

### ISSUE THREAD

**Issue by brampitoyo** [Yoric/redreaming-firefox#2]
https://etherpad.mozilla.org/securefox

Interesting to consider, because most of the features in this EtherPad can be implemented simply by flipping a pref on or off. We could even have a hat that turns all the “paranoid” security features on. Of course, we’ll call it “tinfoil hat”.

One potentially interesting feature is to have a “hatless” Firefox that turns all protection off. A lot of users think that a site is broken if it won’t load video, stylesheet, image and other things. Some of those may in fact be due to various security features (or add-ons) that we have implemented and users have installed (AdBlock comes to mind – sometimes it causes stuff to not play or show up properly).

In the example above, users want to say “Look. I don’t care if I have to see ads or be insecure or something. All I want is for video/content to play/show up, and I’ll use another browser if I need to!”.

So maybe we could say “Notice something broken? Try “hatless”. It’s not something you want to do often, so we should limit its operation. Maybe user can’t browse anywhere else while in “hatless”. Maybe we clear this “hatless” container when it closes. The point is to have a way to solve a frustration.

**Comment by Yoric** [comment]
Added both SecureFox and HatlessFox to the Strategy Document.
